<?php
/**
 * ClassificationModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Together\Taxes\Provider\AvaTax\Swagger
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax API
 *
 * REST interface to Avalara's enterprise tax service, AvaTax.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Together\Taxes\Provider\AvaTax\Swagger;

/**
 * ClassificationModelTest Class Doc Comment
 *
 * @category    Class
 * @description Represents a classification for a given item.
 * @package     Together\Taxes\Provider\AvaTax\Swagger
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClassificationModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ClassificationModel"
     */
    public function testClassificationModel()
    {
    }

    /**
     * Test attribute "product_code"
     */
    public function testPropertyProductCode()
    {
    }

    /**
     * Test attribute "system_code"
     */
    public function testPropertySystemCode()
    {
    }
}
