<?php
/**
 * AuditModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax API
 *
 * REST interface to Avalara's enterprise tax service, AvaTax.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AuditModelTest Class Doc Comment
 *
 * @category    Class
 * @description Provides detailed information about an API call.                The information on this record was captured by AvaTax when your API call was made.  If you are unsure why you  received an error, you can fetch these audit objects and examine the &#x60;RequestUrl&#x60;, &#x60;RequestBody&#x60;, and &#x60;ErrorMessage&#x60;  fields to determine root cause for the error.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuditModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AuditModel"
     */
    public function testAuditModel()
    {
    }

    /**
     * Test attribute "transaction_id"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "account_id"
     */
    public function testPropertyAccountId()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "machine_name"
     */
    public function testPropertyMachineName()
    {
    }

    /**
     * Test attribute "client_name"
     */
    public function testPropertyClientName()
    {
    }

    /**
     * Test attribute "client_version"
     */
    public function testPropertyClientVersion()
    {
    }

    /**
     * Test attribute "adapter_name"
     */
    public function testPropertyAdapterName()
    {
    }

    /**
     * Test attribute "adapter_version"
     */
    public function testPropertyAdapterVersion()
    {
    }

    /**
     * Test attribute "server_name"
     */
    public function testPropertyServerName()
    {
    }

    /**
     * Test attribute "server_version"
     */
    public function testPropertyServerVersion()
    {
    }

    /**
     * Test attribute "reference_id"
     */
    public function testPropertyReferenceId()
    {
    }

    /**
     * Test attribute "severity_level_id"
     */
    public function testPropertySeverityLevelId()
    {
    }

    /**
     * Test attribute "server_timestamp"
     */
    public function testPropertyServerTimestamp()
    {
    }

    /**
     * Test attribute "server_duration"
     */
    public function testPropertyServerDuration()
    {
    }

    /**
     * Test attribute "service_name"
     */
    public function testPropertyServiceName()
    {
    }

    /**
     * Test attribute "operation"
     */
    public function testPropertyOperation()
    {
    }

    /**
     * Test attribute "reference_code"
     */
    public function testPropertyReferenceCode()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }

    /**
     * Test attribute "audit_message"
     */
    public function testPropertyAuditMessage()
    {
    }

    /**
     * Test attribute "load_balancer_duration"
     */
    public function testPropertyLoadBalancerDuration()
    {
    }

    /**
     * Test attribute "record_count"
     */
    public function testPropertyRecordCount()
    {
    }

    /**
     * Test attribute "reference_authorization"
     */
    public function testPropertyReferenceAuthorization()
    {
    }

    /**
     * Test attribute "is_queued"
     */
    public function testPropertyIsQueued()
    {
    }

    /**
     * Test attribute "database_call_count"
     */
    public function testPropertyDatabaseCallCount()
    {
    }

    /**
     * Test attribute "database_call_duration"
     */
    public function testPropertyDatabaseCallDuration()
    {
    }

    /**
     * Test attribute "remote_call_duration"
     */
    public function testPropertyRemoteCallDuration()
    {
    }

    /**
     * Test attribute "events"
     */
    public function testPropertyEvents()
    {
    }

    /**
     * Test attribute "request_url"
     */
    public function testPropertyRequestUrl()
    {
    }

    /**
     * Test attribute "request_body"
     */
    public function testPropertyRequestBody()
    {
    }

    /**
     * Test attribute "response_status"
     */
    public function testPropertyResponseStatus()
    {
    }

    /**
     * Test attribute "response_body"
     */
    public function testPropertyResponseBody()
    {
    }

    /**
     * Test attribute "remote_calls"
     */
    public function testPropertyRemoteCalls()
    {
    }
}
