<?php
/**
 * CommunicationsTransactionTypeModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax API
 *
 * REST interface to Avalara's enterprise tax service, AvaTax.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CommunicationsTransactionTypeModelTest Class Doc Comment
 *
 * @category    Class
 * @description Represents information about a type of telecommunications transaction
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CommunicationsTransactionTypeModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CommunicationsTransactionTypeModel"
     */
    public function testCommunicationsTransactionTypeModel()
    {
    }

    /**
     * Test attribute "transaction_type_id"
     */
    public function testPropertyTransactionTypeId()
    {
    }

    /**
     * Test attribute "ava_tax_communications_transaction_type"
     */
    public function testPropertyAvaTaxCommunicationsTransactionType()
    {
    }
}
