<?php
/**
 * CreateOrAdjustTransactionModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax API
 *
 * REST interface to Avalara's enterprise tax service, AvaTax.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateOrAdjustTransactionModelTest Class Doc Comment
 *
 * @category    Class
 * @description Create or adjust transaction model
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateOrAdjustTransactionModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateOrAdjustTransactionModel"
     */
    public function testCreateOrAdjustTransactionModel()
    {
    }

    /**
     * Test attribute "adjustment_reason"
     */
    public function testPropertyAdjustmentReason()
    {
    }

    /**
     * Test attribute "adjustment_description"
     */
    public function testPropertyAdjustmentDescription()
    {
    }

    /**
     * Test attribute "create_transaction_model"
     */
    public function testPropertyCreateTransactionModel()
    {
    }
}
