<?php
/**
 * CycleAddOptionModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax API
 *
 * REST interface to Avalara's enterprise tax service, AvaTax.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CycleAddOptionModelTest Class Doc Comment
 *
 * @category    Class
 * @description Model with options for adding a new filing calendar
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CycleAddOptionModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CycleAddOptionModel"
     */
    public function testCycleAddOptionModel()
    {
    }

    /**
     * Test attribute "available"
     */
    public function testPropertyAvailable()
    {
    }

    /**
     * Test attribute "transactional_period_start"
     */
    public function testPropertyTransactionalPeriodStart()
    {
    }

    /**
     * Test attribute "transactional_period_end"
     */
    public function testPropertyTransactionalPeriodEnd()
    {
    }

    /**
     * Test attribute "filing_due_date"
     */
    public function testPropertyFilingDueDate()
    {
    }

    /**
     * Test attribute "cycle_name"
     */
    public function testPropertyCycleName()
    {
    }

    /**
     * Test attribute "frequency_name"
     */
    public function testPropertyFrequencyName()
    {
    }

    /**
     * Test attribute "filing_frequency_code"
     */
    public function testPropertyFilingFrequencyCode()
    {
    }

    /**
     * Test attribute "filing_frequency_id"
     */
    public function testPropertyFilingFrequencyId()
    {
    }

    /**
     * Test attribute "cycle_unavailable_reason"
     */
    public function testPropertyCycleUnavailableReason()
    {
    }

    /**
     * Test attribute "available_location_codes"
     */
    public function testPropertyAvailableLocationCodes()
    {
    }
}
