<?php
/**
 * FilingsCheckupAuthorityModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax API
 *
 * REST interface to Avalara's enterprise tax service, AvaTax.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FilingsCheckupAuthorityModelTest Class Doc Comment
 *
 * @category    Class
 * @description Cycle Safe Expiration results.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FilingsCheckupAuthorityModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FilingsCheckupAuthorityModel"
     */
    public function testFilingsCheckupAuthorityModel()
    {
    }

    /**
     * Test attribute "tax_authority_id"
     */
    public function testPropertyTaxAuthorityId()
    {
    }

    /**
     * Test attribute "location_code"
     */
    public function testPropertyLocationCode()
    {
    }

    /**
     * Test attribute "tax_authority_name"
     */
    public function testPropertyTaxAuthorityName()
    {
    }

    /**
     * Test attribute "tax_authority_type_id"
     */
    public function testPropertyTaxAuthorityTypeId()
    {
    }

    /**
     * Test attribute "jurisdiction_id"
     */
    public function testPropertyJurisdictionId()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "tax_type_id"
     */
    public function testPropertyTaxTypeId()
    {
    }

    /**
     * Test attribute "suggested_forms"
     */
    public function testPropertySuggestedForms()
    {
    }
}
