<?php
/**
 * NexusByTaxFormModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Together\Taxes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax API
 *
 * REST interface to Avalara's enterprise tax service, AvaTax.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Together\Taxes\Model;

use \ArrayAccess;
use \Together\Taxes\ObjectSerializer;

/**
 * NexusByTaxFormModel Class Doc Comment
 *
 * @category Class
 * @description Identifies all nexus that match a particular tax form
 * @package  Together\Taxes
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NexusByTaxFormModel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'NexusByTaxFormModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'form_code' => 'string',
        'company_id' => 'int',
        'nexus_definitions' => '\Together\Taxes\Model\NexusModel[]',
        'company_nexus' => '\Together\Taxes\Model\NexusModel[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'form_code' => null,
        'company_id' => 'int32',
        'nexus_definitions' => null,
        'company_nexus' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'form_code' => 'formCode',
        'company_id' => 'companyId',
        'nexus_definitions' => 'nexusDefinitions',
        'company_nexus' => 'companyNexus'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'form_code' => 'setFormCode',
        'company_id' => 'setCompanyId',
        'nexus_definitions' => 'setNexusDefinitions',
        'company_nexus' => 'setCompanyNexus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'form_code' => 'getFormCode',
        'company_id' => 'getCompanyId',
        'nexus_definitions' => 'getNexusDefinitions',
        'company_nexus' => 'getCompanyNexus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['form_code'] = isset($data['form_code']) ? $data['form_code'] : null;
        $this->container['company_id'] = isset($data['company_id']) ? $data['company_id'] : null;
        $this->container['nexus_definitions'] = isset($data['nexus_definitions']) ? $data['nexus_definitions'] : null;
        $this->container['company_nexus'] = isset($data['company_nexus']) ? $data['company_nexus'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets form_code
     *
     * @return string
     */
    public function getFormCode()
    {
        return $this->container['form_code'];
    }

    /**
     * Sets form_code
     *
     * @param string $form_code The code of the tax form that was requested
     *
     * @return $this
     */
    public function setFormCode($form_code)
    {
        $this->container['form_code'] = $form_code;

        return $this;
    }

    /**
     * Gets company_id
     *
     * @return int
     */
    public function getCompanyId()
    {
        return $this->container['company_id'];
    }

    /**
     * Sets company_id
     *
     * @param int $company_id The company ID of the company that was used to load the companyNexus array.  If this value is null, no company data was loaded.
     *
     * @return $this
     */
    public function setCompanyId($company_id)
    {
        $this->container['company_id'] = $company_id;

        return $this;
    }

    /**
     * Gets nexus_definitions
     *
     * @return \Together\Taxes\Model\NexusModel[]
     */
    public function getNexusDefinitions()
    {
        return $this->container['nexus_definitions'];
    }

    /**
     * Sets nexus_definitions
     *
     * @param \Together\Taxes\Model\NexusModel[] $nexus_definitions A list of all Avalara-defined nexus that are relevant to this tax form
     *
     * @return $this
     */
    public function setNexusDefinitions($nexus_definitions)
    {
        $this->container['nexus_definitions'] = $nexus_definitions;

        return $this;
    }

    /**
     * Gets company_nexus
     *
     * @return \Together\Taxes\Model\NexusModel[]
     */
    public function getCompanyNexus()
    {
        return $this->container['company_nexus'];
    }

    /**
     * Sets company_nexus
     *
     * @param \Together\Taxes\Model\NexusModel[] $company_nexus A list of all currently-defined company nexus that are related to this tax form
     *
     * @return $this
     */
    public function setCompanyNexus($company_nexus)
    {
        $this->container['company_nexus'] = $company_nexus;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


